### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by danielfilho** [McCouman/lcars-bootstrap#1]
hey @McCouman, how can I contact you?

**Comment by McCouman** [comment]
hi i speak german, 
but you can write her :)

**Comment by danielfilho** [comment]
are you still using your `@foocast` twitter account? I just created a podcast, will upload it next week at foocast.io, but I could see you're no longer using the twitter since 2012 :)

**Comment by danielfilho** [comment]
from google translator:

> sind Sie noch mit Ihrem `@foocast` Twitter-Account? Ich habe gerade einen Podcast erstellt, wird es bei foocast.io laden nächste Woche, aber ich konnte sehen, die Sie nicht mehr mit dem twitter seit 2012 sind :)

**Comment by McCouman** [comment]
No problem. I must seek only the account data. Then I send you, with a standard account + password. By that I do not forget, please write to me about mc@wikibyte.org.

**Comment by McCouman** [comment]
i close that - thx for mail :)
